import charImageStub from "@/assets/special/test-alt.png";

// 全キャラクターデータ（CSVベース）
export const allCharacters = [
	{
		company: "スーパーむしず",
		dept: "ファウンダー／店長",
		name: "蟲酸ハシル",
		imagePath: charImageStub,
		symbol: "𓃭",
		mbti: "ENTJ",
		comment: "計画的・指導型・未来志向。カリスマ的で決断力あり。",
	},
	{
		company: "スーパーむしず",
		dept: "副店長",
		name: "原ククル",
		imagePath: charImageStub,
		symbol: "𓃢",
		mbti: "ESFJ",
		comment: "周囲に気を配り、盛り上げ役。社交的で協力的。",
	},
	{
		company: "スーパーむしず",
		dept: "情シス課長",
		name: "異彩ハナツ",
		imagePath: charImageStub,
		symbol: "𓂀",
		mbti: "ISTJ",
		comment: "規則重視・堅実・現実的。決断は理性的で強め。",
	},
	{
		company: "スーパーむしず",
		dept: "総務課員",
		name: "造詣フカコ",
		imagePath: charImageStub,
		symbol: "𓆣",
		mbti: "ENFP",
		comment: "好奇心旺盛・柔軟・フレッシュな発想。場を明るくする。",
	},
	{
		company: "ハヌマン酒造",
		dept: "会長",
		name: "ハヌマーン",
		imagePath: charImageStub,
		symbol: "𓃵",
		mbti: "INTP",
		comment: "理解不能な存在。論理的好奇心と創造性が強く、自由奔放。",
	},
	{
		company: "スーパーむしず",
		dept: "レジ部門",
		name: "薪クベル",
		imagePath: charImageStub,
		symbol: "𓆈",
		mbti: "ISFJ",
		comment: "真面目で忠実、徐々に成長。最年少30歳",
	},
	{
		company: "スーパーむしず",
		dept: "グロサリー部門",
		name: "七度ゴブ",
		imagePath: charImageStub,
		symbol: "𓃰",
		mbti: "ISTJ",
		comment: "安定志向・ルール重視・勤勉で努力家。",
	},
	{
		company: "スーパーむしず",
		dept: "青果部門",
		name: "白妙コロモ",
		imagePath: charImageStub,
		symbol: "𓆏",
		mbti: "ENFP",
		comment: "おどけ担当・場を和ませる・即興で面白がる。",
	},
	{
		company: "スーパーむしず",
		dept: "ベーカリー部門",
		name: "是河ヒヒ",
		imagePath: charImageStub,
		symbol: "𓃗",
		mbti: "ESFP",
		comment: "おちゃめ担当・行動的・空気を読まず笑いを作る。",
	},
	{
		company: "スーパーむしず",
		dept: "精肉部門",
		name: "夏野シンサク",
		imagePath: charImageStub,
		symbol: "𓃙",
		mbti: "ISFP",
		comment: "穏やか・受容的・衝突を避ける安定タイプ。",
	},
	{
		company: "スーパーむしず",
		dept: "鮮魚部門",
		name: "五月雨シキ",
		imagePath: charImageStub,
		symbol: "𓆛",
		mbti: "INTJ",
		comment: "分析・戦略型・冷静。場を俯瞰するタイプ。",
	},
	{
		company: "スーパーむしず",
		dept: "日配部門",
		name: "余韻ヒタル",
		imagePath: charImageStub,
		symbol: "𓋹",
		mbti: "ENTP",
		comment: "魅力的・知的・即興型。状況に応じて対応できる。",
	},
	{
		company: "みょうり商店",
		dept: "レジ部門",
		name: "誉タカキ",
		imagePath: charImageStub,
		symbol: "𓃾",
		mbti: "INTJ",
		comment: "冷静・計算高い・合理的。ライバル的存在。",
	},
	{
		company: "みょうり商店",
		dept: "グロサリー部門",
		name: "冥利ツキル",
		imagePath: charImageStub,
		symbol: "𓃬",
		mbti: "ESTJ",
		comment: "支配的・組織型・命令型。計画に従わせる。",
	},
	{
		company: "みょうり商店",
		dept: "青果部門",
		name: "雨天ケッコウ",
		imagePath: charImageStub,
		symbol: "𓆙",
		mbti: "ENTP",
		comment: "狡猾・奇抜・場をかき乱す。創意工夫型。",
	},
	{
		company: "みょうり商店",
		dept: "ベーカリー部門",
		name: "景勝ナラス",
		imagePath: charImageStub,
		symbol: "𓃝",
		mbti: "ESFP",
		comment: "騒がしい・目立ちたがり・瞬間的に面白いことをする。",
	},
	{
		company: "みょうり商店",
		dept: "精肉部門",
		name: "二晩センジ",
		imagePath: charImageStub,
		symbol: "𓃟",
		mbti: "ISFP",
		comment: "穏やかで協力的・争いを好まず安定。",
	},
	{
		company: "みょうり商店",
		dept: "鮮魚部門",
		name: "白昼ドウドウ",
		imagePath: charImageStub,
		symbol: "𓆜",
		mbti: "INFP",
		comment: "ゆったり・マイペース・自己世界重視。",
	},
	{
		company: "みょうり商店",
		dept: "日配部門",
		name: "蚰蜒ゲジ",
		imagePath: charImageStub,
		symbol: "𓆤",
		mbti: "ESFP",
		comment: "おちゃめ担当・即興・空気を読むより笑いを重視。",
	},
	{
		company: "ハヌマン酒造",
		dept: "商品開発部",
		name: "紙日トエ",
		imagePath: charImageStub,
		symbol: "𓁹",
		mbti: "INTP",
		comment: "理論家・自由思考・独創的で研究重視。",
	},
	{
		company: "ハヌマン酒造",
		dept: "監査課",
		name: "烽火アゲル",
		imagePath: charImageStub,
		symbol: "𓃀",
		mbti: "ISTJ",
		comment: "真面目・規則重視・リスク管理。",
	},
] as const;
